// Generated by CoffeeScript 1.12.7
(function() {
  var CheneySpreadRateModel, McArthurSpreadRateModel, SimpleSpreadRateModel;

  window.Models || (window.Models = {});

  window.Models.simpleSpreadRateModel = SimpleSpreadRateModel = (function() {
    function SimpleSpreadRateModel() {
      this.spread_rate = 100.0;
    }

    SimpleSpreadRateModel.prototype.calculate_spread_rate = function(point, t0, t1) {
      point.theta = 0;
      return point.spread_rate = 1;
    };

    console.log("SimpleSpreadRateModel: " + SimpleSpreadRateModel);
    return SimpleSpreadRateModel;

  })();

  window.Models.McArthurSpreadRateModel = McArthurSpreadRateModel = (function() {
    function McArthurSpreadRateModel() {}

    McArthurSpreadRateModel.prototype.calculate_spread_rate = function(point, t0, t1) {
      var d, d1, d2, ffdi, kbdi, mc, n, p, rh, t, u, w;
      kbdi = point.param('VEGETATION', 'KBDI');
      if (!kbdi) {
        return;
      }
      p = point.param('RAIN', 'precipitation');
      n = point.param('RAIN', 'days_since_rain');
      d1 = 0.191 * (kbdi + 104) * Math.pow(n + 1, 1.5);
      d2 = 3.52 * Math.pow(n + 1, 1.5) + p - 1;
      d = d1 / d2;
      u = point.param('WIND', 'speed_2m');
      rh = point.param('ATMOSPHERE', 'humidity');
      t = point.param('ATMOSPHERE', 'temperature');
      mc = 5.658 + 0.04651 * rh + 0.0003151 * Math.pow(rh, 3) / t - 0.185 * Math.pow(t, 0.77);
      ffdi = 34.81 * Math.exp(0.987 * Math.log(d)) * Math.pow(mc, -2.1) * Math.exp(0.0234 * u);
      w = point.param('VEGETATION', 'w');
      return point.spread_rate = 0.0012 * ffdi * w;
    };

    console.log("McArthurSpreadRateModel: " + McArthurSpreadRateModel);
    return McArthurSpreadRateModel;

  })();

  window.Models.CheneySpreadRateModel = CheneySpreadRateModel = (function() {
    function CheneySpreadRateModel() {}

    CheneySpreadRateModel.prototype.calculate_spread_rate = function(point, t0, t1) {
      var c, dc, dm, grazing, mc, r, u;
      grazing = point.param('VEGETATION', 'grazing');
      if (grazing == null) {
        return;
      }
      u = point.param('WIND', 'speed_2m');
      c = point.param('VEGETATION', 'C');
      mc = point.param('VEGETATION', 'FMC');
      dm = mc < 12 ? Math.exp(-0.108 * mc) : u < 10 ? 0.684 - 0.0342 * mc : 0.547 - 0.0228 * mc;
      dc = c < 20 ? 1.12 / (1 + 59.2 * Math.exp(-0.124 * (c - 50))) : 1.036 / (1 + 103.99 * Math.exp(-0.0996 * (c - 20)));
      r = (function() {
        switch (grazing) {
          case 0:
            if (u < 5) {
              return (0.054 + 0.269 * u) * dm * dc;
            } else {
              return (1.4 + 0.838 * Math.pow(u - 5, 0.844)) * dm * dc;
            }
            break;
          case 1:
            if (u < 5) {
              return (0.054 + 0.209 * u) * dm * dc;
            } else {
              return (1.1 + 0.715 * Math.pow(u - 5, 0.844)) * dm * dc;
            }
            break;
          case 2:
            if (u < 5) {
              return (0.054 + 0.209 * u) * dm * dc;
            } else {
              return (0.55 + 0.357 * Math.pow(u - 5, 0.844)) * dm * dc;
            }
        }
      })();
      return point.spread_rate = r;
    };

    console.log("CheneySpreadRateModel: " + CheneySpreadRateModel);
    return CheneySpreadRateModel;

  })();

}).call(this);
console.log("Very End of File spread_rate_model.js");
