# Same spread_rate for the whole area all the time - MUST change this if you want dynamic parameter input with API from WeatherApp...
# const mcarthur_spread_rate_model = function(point, t0, t1) {

mcarthur_spread_rate_model = ->
  kbdi = document.getElementById('kdbi').value
  # point.param('VEGETATION', 150);
  if !kbdi
    return
  # if no data
  p = document.getElementById('precipitation').value
  # point.param('RAIN', 5);
  n = document.getElementById('daysSinceRain').value
  # point.param('RAIN', 14);
  d1 = 0.191 * (kbdi + 104) * (n + 1) ** 1.5
  d2 = 3.52 * (n + 1) ** 1.5 + p - 1
  d = d1 / d2
  u = document.getElementById('windSpeed').value
  # point.param('WIND', 20); // wind speed
  rh = document.getElementById('relativeHumidity').value
  # point.param('ATMOSPHERE', 50);
  t = document.getElementById('airTemperature').value
  # point.param('ATMOSPHERE', 30);
  mc = 5.658 + 0.04651 * rh + 0.0003151 * rh ** 3 / t - (0.185 * t ** 0.77)
  ffdi = 34.81 * Math.exp(0.987 * Math.log(d)) * mc ** (-2.1) * Math.exp(0.0234 * u)
  w = document.getElementById('w').value
  # point.param('VEGETATION', 1);
  spread_rate = 0.0012 * ffdi * w
  console.log 'spread_rate (McArthur)' + spread_rate
  spread_rate

# ---
# generated by js2coffee 2.2.0