@startuml
'skinparam backgroundColor #EEEBDC

/'
use for testing plantUML:
https://www.plantuml.com/plantuml/uml
'/
Title Sequence Diagram of function calls

User -> UI: click Button
UI -> start_calculation
start_calculation -> UI: ignition coordinates request
start_calculation <-- UI: ignition coordinates response
start_calculation -> cellular_automaton

cellular_automaton -> UI: steps request
cellular_automaton <-- UI: steps response
cellular_automaton -> find_latest_time_in_list_of_ignited_cells
cellular_automaton <-- find_latest_time_in_list_of_ignited_cells: returns Integer value for time

loop Iterations = steps parameter

cellular_automaton -> add_neighbours_to_list

add_neighbours_to_list -> calculate_arrival_time: input is from_cell and to_cell and flat=null 


calculate_arrival_time -> UI: Windspeed request
calculate_arrival_time <-- UI: Windspeed response
calculate_arrival_time -> UI: Winddirection request
calculate_arrival_time <-- UI: Winddirection response
alt if testing
calculate_arrival_time -> simple_spread_rate_model: only for testing
calculate_arrival_time <-- simple_spread_rate_model: returns constant spread rate
else if forest
calculate_arrival_time -> mcarthur_spread_rate_model: if forest (not activated)
mcarthur_spread_rate_model -> UI: parameter request
mcarthur_spread_rate_model <-- UI: parameter response
calculate_arrival_time <-- mcarthur_spread_rate_model: returns spread rate
else if grassland
calculate_arrival_time -> cheney_spread_rate_model: if Grassland (not activated)
cheney_spread_rate_model -> UI: parameter request
cheney_spread_rate_model <-- UI: parameter
calculate_arrival_time <-- cheney_spread_rate_model: returns spread rate
end
calculate_arrival_time -> UI: Slope request (in comments)
calculate_arrival_time <-- UI: response is not yet implemented
calculate_arrival_time -> UI: Aspect request (in comments)
calculate_arrival_time <-- UI: response is not yet implemented
calculate_arrival_time -> UI: Elevation request (in comments)
calculate_arrival_time <-- UI: response is not yet implemented


add_neighbours_to_list <-- calculate_arrival_time: returns arrival_time


cellular_automaton <-- add_neighbours_to_list: returns updated list of ignited 
end



start_calculation <-- cellular_automaton: returns final_list_of_burning_cells


start_calculation -> fill_table
fill_table -> UI: show result
@enduml